services:
  fcp-find-ai-api:
    build:
      target: development
    image: fcp-find-ai-api-development
    ports:
      - '3001:3000'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - '.env'
    environment:
      PORT: 3000
      NODE_ENV: development
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - cdp-tenant

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4564:4510-4564' # external services port range
    env_file:
      - '.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose,dynamodb
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - localstack:/var/lib/localstack
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant
  
  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data
    restart: always

volumes:
  localstack:
  mongodb:

networks:
  cdp-tenant:
    driver: bridge
